sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_958833aacc7d_key -iv $encrypted_958833aacc7d_iv -in multi-k8s-330813-00f1b9760719.json.enc -out multi-k8s-330813-00f1b9760719.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json